'use client'

import React from 'react'
import type { BatchHistoryItem } from './types'

type Props = {
  history: BatchHistoryItem[]
  onView: (batchId: string) => void
}

export default function BatchHistory({ history, onView }: Props) {
  return (
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="mb-4">
        <h3 className="text-lg font-semibold text-slate-900">Batch History</h3>
        <p className="text-sm text-slate-500">Previously generated batches in this session.</p>
      </div>

      <div className="overflow-x-auto rounded-xl border border-slate-200">
        <table className="min-w-full text-left text-sm">
          <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600">
            <tr>
              <th className="px-4 py-3">Batch ID</th>
              <th className="px-4 py-3">Barangay</th>
              <th className="px-4 py-3">Quantity</th>
              <th className="px-4 py-3">Generated By</th>
              <th className="px-4 py-3">Date</th>
              <th className="px-4 py-3">View</th>
            </tr>
          </thead>
          <tbody>
            {history.length ? (
              history.map((item) => (
                <tr key={item.batchId} className="border-t border-slate-100">
                  <td className="px-4 py-3 font-mono text-slate-900">{item.batchId}</td>
                  <td className="px-4 py-3 text-slate-700">{item.barangay}</td>
                  <td className="px-4 py-3 text-slate-700">{item.quantity}</td>
                  <td className="px-4 py-3 text-slate-700">{item.generatedBy}</td>
                  <td className="px-4 py-3 text-slate-700">{item.date}</td>
                  <td className="px-4 py-3">
                    <button
                      type="button"
                      onClick={() => onView(item.batchId)}
                      className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
                      aria-label={`View batch ${item.batchId}`}
                    >
                      View
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={6} className="px-4 py-8 text-center text-sm text-slate-500">
                  No batch history available yet.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </section>
  )
}

