'use client'

import React from 'react'
import type { BatchHistoryItem } from './types'

type Props = {
  history: BatchHistoryItem[]
  onView: (batchId: string) => void
}

export default function BatchHistory({ history, onView }: Props) {
  return (
    <section className="rounded-[2rem] border border-white/80 dark:border-slate-800 bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl flex flex-col overflow-hidden shadow-[0_8px_32px_-8px_rgba(0,0,0,0.08)] transition-colors mb-8">
      <div className="p-5 border-b border-gray-100 dark:border-slate-800 bg-white/40 dark:bg-slate-800/40 flex flex-col sm:flex-row justify-between sm:items-center">
        <div>
          <h3 className="text-sm font-bold text-gray-900 dark:text-gray-100 tracking-wide uppercase">Batch History</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">Previously generated batches in this session.</p>
        </div>
      </div>

      <div className="overflow-x-auto w-full">
        <table className="w-full text-left border-collapse table-fixed min-w-[800px] lg:min-w-0">
          <thead className="bg-white/50 dark:bg-slate-800/50 border-b border-gray-200 dark:border-slate-700 text-[11px] font-bold text-gray-400 dark:text-slate-400 uppercase tracking-wider">
            <tr>
              <th className="px-6 py-4 w-[25%]">Batch ID</th>
              <th className="px-6 py-4 w-[20%]">Barangay</th>
              <th className="px-6 py-4 w-[10%]">Count</th>
              <th className="px-6 py-4 w-[15%]">Generated By</th>
              <th className="px-6 py-4 w-[20%]">Date</th>
              <th className="px-6 py-4 w-[10%] text-right pr-6">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100 dark:divide-slate-800/50 text-sm">
            {history.length ? (
              history.map((item) => (
                <tr key={item.batchId} className="hover:bg-white/60 dark:hover:bg-slate-800/60 transition-colors group">
                  <td className="px-6 py-4 font-mono font-bold text-gray-900 dark:text-gray-100 tracking-wider text-[12px] whitespace-normal break-words">{item.batchId}</td>
                  <td className="px-6 py-4 font-medium text-gray-700 dark:text-gray-300">{item.barangay}</td>
                  <td className="px-6 py-4 font-bold text-gray-800 dark:text-gray-200">{item.quantity}</td>
                  <td className="px-6 py-4 font-medium text-gray-600 dark:text-gray-400 truncate">{item.generatedBy}</td>
                  <td className="px-6 py-4 font-medium text-gray-500 dark:text-slate-400 text-xs whitespace-normal">{item.date}</td>
                  <td className="px-6 py-4 text-right pr-6">
                    <button
                      type="button"
                      onClick={() => onView(item.batchId)}
                      className="rounded-lg border-[1.5px] border-gray-200 dark:border-slate-700 bg-white/50 dark:bg-slate-800/50 px-3 py-1.5 text-xs font-bold text-gray-500 dark:text-gray-300 transition-all hover:bg-gray-50 dark:hover:bg-slate-700 hover:border-gray-300 dark:hover:border-slate-600 hover:text-gray-900 dark:hover:text-white"
                      aria-label={`View batch ${item.batchId}`}
                    >
                      View
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={6} className="px-6 py-12 text-center text-sm text-gray-500 dark:text-gray-400 font-medium">
                  No batch history available yet for this session.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </section>
  )
}

